name: Somato Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Run Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cargo-bins/cargo-binstall@main
      -  run: cargo clippy --all-targets --all-features
      -  run: cargo binstall cargo-audit
      -  run: cargo audit

  analysis:
    name: Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cargo-bins/cargo-binstall@main
      -  run: cargo binstall cargo-tarpaulin
      -  run: cargo tarpaulin

  build_and_test:
    name: Somato All Toolchains
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
  
  build_for_windows:
    name: Build for Windows
    runs-on: ubuntu-latest
    env:
      TARGET: x86_64-pc-windows-gnu
    steps:
      - run: sudo apt update
      - run: sudo apt install mingw-w64 -y
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: $TARGET

      - run: rustup --version
      - name: Setup Cache
        uses: Swatinem/rust-cache@v2

      - uses: actions/checkout@v4

      - name: Build Binary
        run: cargo build --verbose --locked --release --target $TARGET
      - run: ls -lah target/$TARGET/
      - run: ls -lah target/$TARGET/release ; echo true
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: somato.exe
          path: target/$TARGET/release/somato.exe
